import argparse

parser = argparse.ArgumentParser(description='TrCLIP-VAD')
parser.add_argument('--seed', default=234, type=int)
parser.add_argument('--embed-dim', default=512, type=int)
parser.add_argument('--visual-length', default=256, type=int)
parser.add_argument('--visual-width', default=512, type=int)
parser.add_argument('--visual-head', default=1, type=int)
parser.add_argument('--visual-layers', default=1, type=int)
parser.add_argument('--text-features', default=768, type=int)
parser.add_argument('--attn-window', default=64, type=int)
parser.add_argument('--prompt-prefix', default=10, type=int)
parser.add_argument('--prompt-postfix', default=10, type=int)
parser.add_argument('--classes-num', default=7, type=int)

parser.add_argument('--max-epoch', default=10, type=int)
parser.add_argument('--model-path', default='/root/autodl-tmp/model/xd/model_xd.pth')
parser.add_argument('--use-checkpoint', default=False, type=bool)
parser.add_argument('--checkpoint-path', default='/root/autodl-tmp/model/xd/checkpoint_xd.pth')
parser.add_argument('--batch-size', default=96, type=int)
parser.add_argument('--visual-train-list', default='/root/autodl-tmp/code/list/xd_CLIP_rgb.csv')
parser.add_argument('--text-train-list', default='/root/autodl-tmp/code/list/xd_text.csv')
parser.add_argument('--visual-test-list', default='/root/autodl-tmp/code/list/xd_CLIP_rgbtest.csv')
parser.add_argument('--text-test-list', default='/root/autodl-tmp/code/list/xd_text_test.csv')
parser.add_argument('--gt-path', default='/root/autodl-tmp/code/list/gt.npy')
parser.add_argument('--gt-segment-path', default='/root/autodl-tmp/code/list/gt_segment.npy')
parser.add_argument('--gt-label-path', default='/root/autodl-tmp/code/list/gt_label.npy')

parser.add_argument('--lr', default=5e-6)
parser.add_argument('--scheduler-rate', default=0.1)
parser.add_argument('--scheduler-milestones', default=[3, 6, 10])

parser.add_argument('--seq_len', type=int, default=256, help='input sequence length')
parser.add_argument('--pred_len', type=int, default=512, help='prediction sequence length')
parser.add_argument('--n1', type=int, default=512, help='First Embedded representation')
parser.add_argument('--n2', type=int, default=256, help='Second Embedded representation')

parser.add_argument('--ch_ind', type=int, default=0, help='Channel Independence; True 1 False 0')
parser.add_argument('--residual', type=int, default=1, help='Residual Connection; True 1 False 0')
parser.add_argument('--d_state', type=int, default=256, help='d_state parameter of Mamba')
parser.add_argument('--dconv', type=int, default=2, help='d_conv parameter of Mamba')
parser.add_argument('--e_fact', type=int, default=1, help='expand factor parameter of Mamba')
parser.add_argument('--enc_in', type=int, default=512, help='encoder input size')
parser.add_argument('--dropout', type=float, default=0.05, help='dropout')